#!/usr/bin/env sh

#
# Installs ydf on the system
#

set -eu

# ENV VARS
if [ -n "$DESTDIR" ]; then
  DESTDIR="$(realpath "$DESTDIR")"
fi

mkdir -p "${DESTDIR}/etc"
cp -vr src/etc/ydf "${DESTDIR}/etc"

install -v -Dm644 src/etc/skel/.ydf.env \
  "${DESTDIR}/etc/skel/.ydf.env"

mkdir -p "${DESTDIR}/usr/lib"
cp -vr src/usr/lib/ydf "${DESTDIR}/usr/lib"

install -v -Dm755 src/usr/bin/ydf \
  "${DESTDIR}/usr/bin/ydf"

install -v -Dm644 src/usr/share/licenses/ydf/LICENSE \
  "${DESTDIR}/usr/share/licenses/ydf/LICENSE"

echo
echo '>> INSTALLED SUCCESSFULLY'

cat <<MSG

>> CONFIGURE ydf:
# Add "${DESTDIR}/usr/bin to your PATH if needed

# Copy the config to your home directory
cp ${DESTDIR}/etc/skel/.ydf.env ~/

# Edit it
vim ~/.ydf.env
MSG
