# grep -Po '^\S+(?=:)' Makefile.vedv | tr '\n' ' '
.PHONY: test-unit test-integration test-functional test-all test-suite test-name

test-unit:
	./tools/bats-unit

test-integration:
	./tools/bats-integration

test-functional:
	./tools/bats-functional

test-all:
	./tools/bats --recursive tests

test-suite:
	./tools/bats $(u)

test-name:
	./tools/bats --filter '$(n)' $(u)
