#!/usr/bin/env bash
#
# Install optional dependencies for manjaro
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

# ENVIROMENT VARIABLES
readonly IMAGE_BUILDING="${IMAGE_BUILDING:-false}"

# Install yay, snapd, docker,docker-compose
sudo pacman -Syyu --noconfirm --needed make "${PKG_OPT_MANJARO_PACMAN[@]}"

# Configure snap
sudo systemctl enable apparmor
sudo systemctl enable snapd.apparmor
sudo systemctl enable snapd

if [[ "$IMAGE_BUILDING" == false ]]; then
  sudo systemctl start apparmor
  sudo systemctl start snapd.apparmor
  sudo systemctl start snapd
fi

sudo ln -vs /var/lib/snapd/snap /snap

echo ">>Attention: log out and back in again, or restart your system, to ensure snap’s paths are updated correctly"

# sudo snap install core

# Configure docker

sudo systemctl enable docker

if [[ "$IMAGE_BUILDING" == false ]]; then
  sudo systemctl start docker
fi

sudo groupadd docker || :
sudo usermod -aG docker "$USER"

# Install YZSH

if [[ -f .ydf.env ]]; then
  # shellcheck source=../.ydf.env
  source .ydf.env

  ## DOWNLOAD USER YZSH DATA
  if [[ -n "${YDF_YZSH_DATA_REPOSITORY_URL:-}" ]]; then
    git clone "$YDF_YZSH_DATA_REPOSITORY_URL" "$YDF_YZSH_DATA_DIR"
  fi
##

fi

cd "$(mktemp -d)"

for pkg in "${PKG_OPT_MANJARO_GITHUB[@]}"; do
  (
    git clone "https://github.com/${pkg}.git" && cd "${pkg#*/}"
    make install
  )
done
