#!/usr/bin/env bash
#
# Install manjaro runtime packages
#

set -eu
# shellcheck source=../packages.env
. ./packages.env

sudo pacman -Syu --noconfirm --needed yay

yay -Sy --noconfirm --needed "${PKG_RUN_MANJARO_PACMAN[@]}"
