#!/usr/bin/env bash
#
# Install ubuntu runtime packages
#

set -eu
# shellcheck source=../packages.env
. ./packages.env

export DEBIAN_FRONTEND=noninteractive

sudo -E apt-get update -y &&
  sudo -E apt-get upgrade -y

sudo -E apt-get install -y "${PKG_RUN_UBUNTU_APT[@]}"
