#!/usr/bin/env bash
#
# Install optional dependencies for ubuntu
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

# ENVIROMENT VARIABLES
readonly IMAGE_BUILDING="${IMAGE_BUILDING:-false}"

export DEBIAN_FRONTEND=noninteractive

sudo -E apt-get update -y &&
  sudo -E apt-get upgrade -y

# Install flatpak
sudo -E add-apt-repository ppa:flatpak/stable -y &&
  sudo -E apt-get update -y &&
  sudo -E apt-get install flatpak -y &&
  sudo -H flatpak remote-add --if-not-exists \
    flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install docker

## Add Docker's official GPG key:
sudo -E apt-get update -y
sudo -E apt-get install -y ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
  sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

## Add the repository to Apt sources:
echo \
  "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  \"$(. /etc/os-release && echo "$VERSION_CODENAME")\" stable" |
  sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
sudo -E apt-get update -y

## Install
sudo -E apt-get install -y docker-ce docker-ce-cli \
  containerd.io docker-buildx-plugin docker-compose-plugin

sudo systemctl enable docker

if [[ "$IMAGE_BUILDING" == false ]]; then
  sudo systemctl start docker
fi

sudo groupadd docker || :
sudo usermod -aG docker "$USER"

# Install YZSH

if [[ -f .ydf.env ]]; then
  # shellcheck source=../.ydf.env
  source .ydf.env

  ## DOWNLOAD USER YZSH DATA
  if [[ -n "${YDF_YZSH_DATA_REPOSITORY_URL:-}" ]]; then
    git clone "$YDF_YZSH_DATA_REPOSITORY_URL" "$YDF_YZSH_DATA_DIR"
  fi
##

fi

sudo -E apt-get install -y make git
cd "$(mktemp -d)"
git clone https://github.com/yunielrc/yzsh.git && cd yzsh
make install
