#!/usr/bin/env bash
#
# Install optional dependencies for ubuntu
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

# ENVIROMENT VARIABLES
readonly IMAGE_BUILDING="${IMAGE_BUILDING:-false}"

export DEBIAN_FRONTEND=noninteractive

sudo -E apt-get update -y &&
  sudo -E apt-get upgrade -y

sudo -E apt-get install -y dconf-cli

# Install flatpak
sudo -E add-apt-repository ppa:flatpak/stable -y &&
  sudo -E apt-get update -y &&
  sudo -E apt-get install flatpak -y &&
  sudo -H flatpak remote-add --if-not-exists \
    flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install docker
curl -fsSL https://get.docker.com | sudo -E sh -

sudo systemctl enable docker

if [[ "$IMAGE_BUILDING" == false ]]; then
  sudo systemctl start docker
fi

sudo groupadd docker || :
sudo usermod -aG docker "$USER"

# Install YZSH

if [[ -f .ydf.env ]]; then
  # shellcheck source=../.ydf.env
  source .ydf.env

  ## DOWNLOAD USER YZSH DATA
  if [[ -n "${YDF_YZSH_DATA_REPOSITORY_URL:-}" ]]; then
    git clone "$YDF_YZSH_DATA_REPOSITORY_URL" "$YDF_YZSH_DATA_DIR"
  fi
##

fi

sudo -E apt-get install -y make git
cd "$(mktemp -d)"
git clone https://github.com/yunielrc/yzsh.git && cd yzsh
make install
