#!/usr/bin/env bash
#
# Install optional dependencies for ubuntu
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

# ENVIROMENT VARIABLES
readonly IMAGE_BUILDING="${IMAGE_BUILDING:-false}"

export DEBIAN_FRONTEND=noninteractive

sudo -E apt-get update -y &&
  sudo -E apt-get upgrade -y

# Add apt repositories

## Add flatpak repo
sudo -E add-apt-repository ppa:flatpak/stable -y &&
  sudo -E apt-get update -y

## Add docker's official GPG key
sudo -E apt-get update -y
sudo -E apt-get install -y ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
  sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

## Add docker repo
echo \
  "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  \"$(. /etc/os-release && echo "$VERSION_CODENAME")\" stable" |
  sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
sudo -E apt-get update -y

# Install Packages

## apt packages
sudo -E apt-get install -y "${PKG_OPT_UBUNTU_APT[@]}"

## github packages
sudo -E apt-get install -y make git

cd "$(mktemp -d)"

for pkg in "${PKG_OPT_MANJARO_GITHUB[@]}"; do
  (
    git clone "https://github.com/${pkg}.git" && cd "${pkg#*/}"
    make install
  )
done
cd -

# Configure

## configure flatpak
sudo -H flatpak remote-add --if-not-exists \
  flathub https://dl.flathub.org/repo/flathub.flatpakrepo

## configure docker
sudo systemctl enable docker

if [[ "$IMAGE_BUILDING" == false ]]; then
  sudo systemctl start docker
fi

sudo groupadd docker || :
sudo usermod -aG docker "$USER"

## configure YZSH

if [[ -f .ydf.env ]]; then
  # shellcheck source=../.ydf.env
  source .ydf.env

  ## DOWNLOAD USER YZSH DATA
  if [[ -n "${YDF_YZSH_DATA_REPOSITORY_URL:-}" ]]; then
    git clone "$YDF_YZSH_DATA_REPOSITORY_URL" "$YDF_YZSH_DATA_DIR"
  fi
##

fi
