#!/usr/bin/env bash
#
# List manjaro dev dependencies
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

echo "# SYSTEM: $(uname -a)"

echo '# YAY'
if [[ "${IMAGE_BUILDING:-false}" == false ]]; then
  pacman --color never -Q vedv-git "${PKG_DEV_MANJARO_YAY[@]}"
else
  pacman --color never -Q "${PKG_DEV_MANJARO_YAY[@]}"
fi

echo '# NPM'
npm list -g |
  grep -Po '\s\K.*' |
  grep -E "$(tr ' ' '|' <<<"${PKG_DEV_MANJARO_NPM[*]}")"
