#!/usr/bin/env bash
#
# List manjaro prod dependencies
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

echo "# SYSTEM: $(uname -a)"

echo '# PACMAN'
pacman --color never -Q bash snapd docker docker-compose "${PKG_RUN_MANJARO_YAY[@]}"

echo '# GITHUB'
cat <<EOF
yunielrc/yzsh
EOF
