#!/usr/bin/env bash
#
# List manjaro prod dependencies
#

set -eu

echo "# SYSTEM: $(uname -a)"

echo '# PACMAN'
pacman --color never -Q yay snapd docker docker-compose

echo '# GITHUB'
cat <<EOF
yunielrc/yzsh
EOF
