#!/usr/bin/env bash
#
# List manjaro runtime dependencies
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

echo "# SYSTEM: $(uname -a)"

echo '# PACMAN'
pacman --color never -Q "${PKG_RUN_MANJARO_PACMAN[@]}"

# echo '# YAY'
# pacman --color never -Q "${PKG_RUN_MANJARO_YAY[@]}"
