#!/usr/bin/env bash
#
# List manjaro prod dependencies
#

set -eu

# shellcheck source=../packages.env
. ./packages.env

echo "# SYSTEM: $(uname -a)"

echo '# PACMAN'
pacman --color never -Q "${PKG_OPT_MANJARO_PACMAN[@]}"

echo '# GITHUB'
tr ' ' '\n' <<<"${PKG_OPT_MANJARO_GITHUB[*]}"
