#!/usr/bin/env bash
#
# Update runtime and optional packages versions files from Test OS
#
# This script should be executed after each successful test-all run
#

set -eu

readonly header="##
## All tests must succeed before updating these files in order to answer
## the question
##
## What are the packages with which the application worked well?
##
"

# MANDATORY ENV VARS
readonly TEST_OS

if [[ -z "$TEST_OS" ]]; then
  echo "TEST_OS env var is not set" >&2
  exit 1
fi

if [[ ! -f "./tools/list-pkgs-run-${TEST_OS}" ]]; then
  echo "File ./tools/list-pkgs-run-${TEST_OS} does not exist" >&2
  exit 1
fi

{
  echo "$header"
  bash "./tools/list-pkgs-run-${TEST_OS}"
} >"packages-run-${TEST_OS}.versions"

{
  echo "$header"
  bash "./tools/list-pkgs-opt-${TEST_OS}"
} >"packages-opt-${TEST_OS}.versions"

git add \
  "packages-run-${TEST_OS}.versions" \
  "packages-opt-${TEST_OS}.versions"
